kits:
  - name: Unsere Zeit
    slot: 50
    click:
      tempo: 160
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Stille Helden
    slot: 51
    click:
      tempo: 182
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Hey Junge
    slot: 52
    click:
      tempo: 170
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Hallo Spacko
    slot: 53
    click:
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Droge
    slot: 54
    click:
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }