kits:
  - name: Unsere Zeit
    slot: 50
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 160
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Stille Helden
    slot: 51
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 182
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Hey Junge
    slot: 52
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 170
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Hallo Spacko
    slot: 53
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Droge
    slot: 54
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 150
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Barbie
    slot: 55
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Kat.S.8
    slot: 56
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Das System
    slot: 57
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Nein
    slot: 58
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 150
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Diese Welt
    slot: 59
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Fr.d.13.
    slot: 60
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Schlag Dich selbst
    slot: 61
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Wahre Freunde
    slot: 62
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 160
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Jeder gg jeden
    slot: 63
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 145
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Getrennte Wege
    slot: 64
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 95
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Klaus
    slot: 65
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 100
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Kenneth's Song
    slot: 66
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Facebook
    slot: 67
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Morgen
    slot: 68
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 130
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Seit j. Maerz
    slot: 69
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Nachwuchs-Nazis
    slot: 70
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Maerchenwelt
    slot: 71
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 150
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Alkohol
    slot: 72
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 120
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Hochseil
    slot: 73
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 150
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Danke
    slot: 74
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 110
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
  - name: Pop-Kommerz
    slot: 75
    click:
      mode: 0
      sound: 0
      volume: 0
      tempo: 140
      startPad: { from: 1, to: 1 }
    padLinks:
      - { padIndex: 0, tx: 1, rx: 0 }
      - { padIndex: 1, tx: 0, rx: 1 }
